name: YouTube Auto Visit

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=Km-HyBwxcR8'

jobs:
  visit-youtube:
    strategy:
      matrix:
        os: [windows-latest, macos-14, macos-13, ubuntu-latest, ubuntu-arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          npm init -y
          npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth fs axios

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          npm init -y
          npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth fs axios

      - name: Create Puppeteer script
        run: |
          mkdir -p scripts screenshots
          cat > scripts/youtube-visit.js << 'EOL'
          const puppeteer = require('puppeteer-extra');
          const StealthPlugin = require('puppeteer-extra-plugin-stealth');
          const fs = require('fs');

          puppeteer.use(StealthPlugin());

          async function visitYouTube(videoUrl) {
              console.log(`Visiting YouTube: ${videoUrl}`);

              const browser = await puppeteer.launch({
                  headless: "new",
                  ignoreHTTPSErrors: true,
                  executablePath: require('puppeteer').executablePath(),
                  args: [
                      '--no-sandbox',
                      '--disable-setuid-sandbox',
                      '--disable-dev-shm-usage',
                      '--disable-gpu'
                  ]
              });

              const page = await browser.newPage();
              try {
                  await page.goto(videoUrl, { waitUntil: 'networkidle2', timeout: 60000 });
                  await page.screenshot({ path: `./screenshots/youtube_${Date.now()}.png` });
              } catch (error) {
                  console.error("Error visiting YouTube:", error.message);
              } finally {
                  await browser.close();
              }
          }

          async function run() {
              const videoUrl = process.argv[2] || "https://www.youtube.com/watch?v=Km-HyBwxcR8";
              await visitYouTube(videoUrl);
          }

          run().catch(console.error);
          EOL

      - name: Run Puppeteer script
        run: |
          VIDEO_URL="${{ github.event.inputs.video_url || 'https://www.youtube.com/watch?v=Km-HyBwxcR8' }}"
          echo "Visiting: $VIDEO_URL"
          node scripts/youtube-visit.js "$VIDEO_URL" | tee script_output.log

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: youtube-debug-artifacts-${{ matrix.os }}
          path: |
            screenshots/
            *.log
          retention-days: 7
