name: YouTube Auto Visit

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F'

jobs:
  visit-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth fs debug

      - name: Create Puppeteer script
        run: |
          mkdir -p scripts screenshots
          cat > scripts/youtube-visit.js << 'EOL'
          const puppeteer = require('puppeteer-extra');
          const StealthPlugin = require('puppeteer-extra-plugin-stealth');
          const fs = require('fs');

          puppeteer.use(StealthPlugin());

          // Helper sleep function.
          function sleep(ms) {
              return new Promise(resolve => setTimeout(resolve, ms));
          }

          // Function to click on cookie consent if present.
          async function acceptCookies(page) {
              try {
                  // Look for any button with "agree" or "accept" in its inner text.
                  const buttonHandle = await page.evaluateHandle(() => {
                      const buttons = Array.from(document.querySelectorAll('button'));
                      return buttons.find(btn => /agree|accept/i.test(btn.innerText));
                  });
                  if (buttonHandle) {
                      console.log("Cookie consent button found. Clicking it...");
                      await page.evaluate(() => {
                          const buttons = Array.from(document.querySelectorAll('button'));
                          const btn = buttons.find(btn => /agree|accept/i.test(btn.innerText));
                          if (btn) btn.click();
                      });
                      // Give a moment for the consent to process.
                      await sleep(2000);
                      await safeScreenshot(page, `./screenshots/youtube_cookies_accepted_${Date.now()}.png`);
                  } else {
                      console.log("No cookie consent prompt found.");
                  }
              } catch (e) {
                  console.error("Error while accepting cookies:", e.message);
              }
          }

          // Use a static list of known proxies.
          async function getProxies() {
              const staticProxies = [
                  "18.169.83.87:1080",
                  "20.27.86.185:8080",
                  "120.28.210.205:9000",
                  "37.46.62.98:8080",
                  "36.89.251.14:8080",
                  "52.26.114.229:1080",
                  "177.234.250.58:999",
                  "103.228.243.29:8080",
                  "45.140.143.77:18080",
                  "103.245.205.226:6969",
                  "13.234.24.116:80",
                  "45.22.209.157:8888",
                  "103.85.117.6:8080",
                  "38.250.119.207:999",
                  "103.159.96.146:3128",
                  "103.10.231.189:8080",
                  "34.141.27.50:3128",
                  "186.96.50.113:999",
                  "15.206.25.41:1080",
                  "103.144.181.74:80",
                  "4.36.157.45:8080",
                  "103.134.47.8:8080",
                  "188.125.169.144:8080",
                  "103.190.60.29:9090",
                  "103.120.76.94:2024",
                  "186.192.78.7:8080",
                  "187.111.144.102:8080",
                  "190.97.238.62:999",
                  "201.222.28.37:8080",
                  "103.143.168.58:84",
                  "212.174.44.2:8080",
                  "203.76.120.118:8080",
                  "204.199.72.162:999",
                  "31.40.248.2:8080",
                  "191.253.39.82:8080",
                  "202.40.185.247:100",
                  "103.227.107.4:1111",
                  "81.223.55.43:8080"
              ];
              console.log(`Using static proxy list with ${staticProxies.length} proxies.`);
              return staticProxies;
          }

          // Enhanced test for a single proxy by checking navigation and page title.
          async function testProxy(proxy) {
              let browser;
              try {
                  console.log(`Testing proxy ${proxy}...`);
                  const startTime = Date.now();
                  browser = await puppeteer.launch({
                      headless: "new",
                      ignoreHTTPSErrors: true,
                      executablePath: require('puppeteer').executablePath(),
                      args: [
                          `--proxy-server=http://${proxy}`,
                          '--ignore-certificate-errors',
                          '--no-sandbox',
                          '--disable-setuid-sandbox',
                          '--disable-dev-shm-usage',
                          '--disable-gpu'
                      ]
                  });
                  const page = await browser.newPage();
                  // Load YouTube's homepage with a more lenient timeout (60 seconds).
                  await page.goto('https://www.youtube.com', { waitUntil: 'networkidle2', timeout: 60000 });
                  // Verify page title contains "YouTube".
                  const title = await page.title();
                  const responseTime = Date.now() - startTime;
                  if (!title || !title.includes("YouTube")) {
                      throw new Error(`Page title check failed. Got: ${title}`);
                  }
                  console.log(`Proxy ${proxy} is valid. Response time: ${responseTime}ms`);
                  await browser.close();
                  return true;
              } catch (e) {
                  console.error(`Proxy ${proxy} is invalid: ${e.message}`);
                  if (browser) {
                      try { await browser.close(); } catch (err) {}
                  }
                  return false;
              }
          }

          // Rapidly test proxies using concurrency.
          async function validateProxies(proxies, concurrency = 50) {
              const validProxies = [];
              let index = 0;
              async function worker() {
                  while (index < proxies.length) {
                      const currentIndex = index++;
                      const proxy = proxies[currentIndex];
                      if (await testProxy(proxy)) {
                          validProxies.push(proxy);
                      }
                  }
              }
              const workers = [];
              for (let i = 0; i < concurrency; i++) {
                  workers.push(worker());
              }
              await Promise.all(workers);
              console.log(`Total valid proxies found: ${validProxies.length}`);
              return validProxies;
          }

          // Helper function to safely take a screenshot.
          async function safeScreenshot(page, path) {
              try {
                  await page.screenshot({ path });
                  console.log(`Screenshot taken: ${path}`);
              } catch (err) {
                  console.error(`Failed to take screenshot ${path}: ${err.message}`);
              }
          }

          async function visitYouTube(videoUrl) {
              // Get and validate the static proxies.
              const allProxies = await getProxies();
              if (allProxies.length === 0) {
                  console.warn("No proxies available. Exiting...");
                  return;
              }
              const validProxies = await validateProxies(allProxies, 50);
              if (validProxies.length === 0) {
                  console.warn("No valid proxies found. Exiting...");
                  return;
              }

              // Use a random validated proxy for each iteration (3 iterations).
              for (let i = 0; i < 3; i++) {
                  const proxy = validProxies[Math.floor(Math.random() * validProxies.length)];
                  console.log(`Loop ${i + 1}: Using proxy: ${proxy}`);

                  console.log('Launching browser with proxy...');
                  const browser = await puppeteer.launch({
                      headless: "new",
                      ignoreHTTPSErrors: true,
                      executablePath: require('puppeteer').executablePath(),
                      args: [
                          `--proxy-server=http://${proxy}`,
                          '--ignore-certificate-errors',
                          '--no-sandbox',
                          '--disable-setuid-sandbox',
                          '--disable-dev-shm-usage',
                          '--disable-gpu'
                      ]
                  });
                  const page = await browser.newPage();

                  page.on('error', error => console.error('Page error:', error));
                  page.on('pageerror', error => console.error('Page error:', error));

                  try {
                      // Retry navigation up to 3 times.
                      const maxRetries = 3;
                      let navigated = false;
                      for (let attempt = 1; attempt <= maxRetries; attempt++) {
                          try {
                              console.log(`Loop ${i + 1}: Attempt ${attempt} to visit ${videoUrl}`);
                              await page.goto(videoUrl, { waitUntil: 'networkidle2', timeout: 60000 });
                              navigated = true;
                              break;
                          } catch (navError) {
                              console.error(`Loop ${i + 1}: Attempt ${attempt} failed: ${navError.message}`);
                              if (attempt < maxRetries) {
                                  console.log("Retrying in 5 seconds...");
                                  await sleep(5000);
                              } else {
                                  throw navError;
                              }
                          }
                      }
                      if (!navigated) {
                          throw new Error("Navigation failed after maximum retries.");
                      }

                      await safeScreenshot(page, `./screenshots/youtube_loaded_${Date.now()}.png`);

                      // Accept cookie consent if prompted.
                      await acceptCookies(page);

                      console.log("Checking if video is already playing...");
                      const isPlaying = await page.evaluate(() => {
                          const video = document.querySelector("video");
                          return video && !video.paused;
                      });

                      if (!isPlaying) {
                          console.log("Video is not playing. Attempting to click Play button...");
                          const playButtonSelectors = [
                              'button[aria-label="Play"]',
                              'button[title="Play (k)"]',
                              '.ytp-play-button'
                          ];
                          let playButton = null;
                          for (const selector of playButtonSelectors) {
                              playButton = await page.$(selector);
                              if (playButton) {
                                  console.log(`Play button found using selector: ${selector}`);
                                  await playButton.click();
                                  console.log("Video started playing.");
                                  await safeScreenshot(page, `./screenshots/youtube_play_clicked_${Date.now()}.png`);
                                  break;
                              }
                          }
                          if (!playButton) {
                              console.warn("Play button not found, skipping play action.");
                          }
                      } else {
                          console.log("Video is already playing. Skipping Play button click.");
                      }

                      console.log("Watching for 31 seconds with periodic screenshots...");
                      for (let t = 5; t <= 31; t += 5) {
                          await sleep(5000);
                          await safeScreenshot(page, `./screenshots/youtube_watch_${t}s_${Date.now()}.png`);
                      }

                      await safeScreenshot(page, `./screenshots/youtube_finished_${Date.now()}.png`);

                      // Save the final HTML page.
                      const finalHtml = await page.content();
                      const htmlFile = `./screenshots/final_page_${Date.now()}.html`;
                      fs.writeFileSync(htmlFile, finalHtml);
                      console.log(`Final HTML page saved: ${htmlFile}`);

                  } catch (error) {
                      console.error("Error during page interaction:", error.message);
                      try {
                          fs.writeFileSync("./screenshots/failure_page_content.html", await page.content());
                      } catch (e) {
                          console.error("Failed to save failure page content:", e.message);
                      }
                      await safeScreenshot(page, "./screenshots/failure_screenshot.png");
                  } finally {
                      console.log("Closing browser...");
                      await browser.close();
                  }
              }
          }

          async function run() {
              const videoUrl = process.argv[2] || "https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F";
              await visitYouTube(videoUrl);
          }

          run().catch(error => {
              console.error("Script failed:", error.message);
          });
          EOL

      - name: Run Puppeteer script
        run: |
          VIDEO_URL="${{ github.event.inputs.video_url || 'https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F' }}"
          echo "Visiting: $VIDEO_URL"
          node scripts/youtube-visit.js "$VIDEO_URL" | tee script_output.log

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: youtube-debug-artifacts
          path: |
            screenshots/
            *.log
            failure_page_content.html
            failure_screenshot.png
          retention-days: 7
