name: YouTube Auto Visit

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F'

jobs:
  visit-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Initializing npm project..."
          npm init -y
          echo "Installing Puppeteer..."
          npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth fs debug

      - name: Load YouTube cookies from GitHub Secret
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" | base64 --decode > cookies.json || echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.json
        env:
          YOUTUBE_COOKIES: "${{ secrets.YOUTUBE_COOKIES }}"

      - name: Create Puppeteer script
        run: |
          mkdir -p scripts screenshots
          cat > scripts/youtube-visit.js << 'EOL'
          const puppeteer = require('puppeteer-extra');
          const StealthPlugin = require('puppeteer-extra-plugin-stealth');
          const fs = require('fs');

          puppeteer.use(StealthPlugin());

          async function visitYouTube(videoUrl) {
              console.log('Launching browser...');
              const browser = await puppeteer.launch({
                  headless: false,
                  executablePath: require('puppeteer').executablePath(),
                  args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
              });
              const page = await browser.newPage();

              console.log('Setting up user agent and viewport...');
              await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36");
              await page.setViewport({ width: 1280, height: 800 });
              
              console.log('Loading cookies...');
              const cookies = JSON.parse(fs.readFileSync('./cookies.json', 'utf8'));
              await page.setCookie(...cookies);
              
              console.log('Checking if user is logged in...');
              await page.goto('https://www.youtube.com', { waitUntil: 'networkidle2', timeout: 60000 });
              const userLoggedIn = await page.evaluate(() => {
                  return document.querySelector("a[href='/logout'], a[href*='signout'], a[href*='/logout'], button[aria-label='Google Account']") !== null;
              });
              console.log(`User logged in: ${userLoggedIn}`);
              if (!userLoggedIn) {
                  console.warn('User is not logged in! Check your stored cookies.');
              }
              
              for (let i = 0; i < 3; i++) {
                  console.log(`Loop ${i + 1}: Visiting ${videoUrl}`);
                  try {
                      await page.goto(videoUrl, { waitUntil: 'networkidle2', timeout: 60000 });
                      console.log('Page loaded successfully.');
                      
                      console.log('Simulating human interaction...');
                      await page.mouse.move(500, 500);
                      await page.mouse.click(500, 500);
                      await page.evaluate(() => {
                          window.scrollBy(0, 100);
                      });
                      
                      console.log('Checking if video is already playing...');
                      const isPlaying = await page.evaluate(() => {
                          const video = document.querySelector('video');
                          return video && !video.paused;
                      });
                      
                      if (!isPlaying) {
                          console.log('Video is not playing. Attempting to click Play button...');
                          const playButtonSelectors = [
                              'button[aria-label="Play"]',
                              'button[title="Play (k)"]',
                              '.ytp-play-button'
                          ];
                          let playButton = null;
                          for (const selector of playButtonSelectors) {
                              playButton = await page.$(selector);
                              if (playButton) {
                                  console.log(`Play button found using selector: ${selector}`);
                                  await playButton.click();
                                  console.log('Video started playing.');
                                  break;
                              }
                          }
                          if (!playButton) {
                              console.warn('Play button not found, skipping play action.');
                          }
                      } else {
                          console.log('Video is already playing. Skipping Play button click.');
                      }
                      
                      console.log('Waiting for 40 seconds to ensure view is registered...');
                      await new Promise(resolve => setTimeout(resolve, 40000));
                      
                      await page.screenshot({ path: `./screenshots/youtube_after_play_${Date.now()}.png` });
                  } catch (error) {
                      console.error('Error during page interaction:', error.message);
                      fs.writeFileSync('./screenshots/failure_page_content.html', await page.content());
                      await page.screenshot({ path: './screenshots/failure_screenshot.png' });
                  }
              }

              console.log('Closing browser...');
              await browser.close();
          }

          async function run() {
              const videoUrl = process.argv[2] || 'https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F';
              await visitYouTube(videoUrl);
          }

          run().catch(error => {
              console.error('Script failed:', error.message);
          });
          EOL

      - name: Run Puppeteer script
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          VIDEO_URL="${{ github.event.inputs.video_url || 'https://www.youtube.com/watch?v=fuMMSpbPPQs&list=PLaHqwgkhNP9GzvPkj7maeLszT4Xp7F58F' }}"
          echo "Visiting: $VIDEO_URL"
          node scripts/youtube-visit.js "$VIDEO_URL" | tee script_output.log

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: youtube-debug-artifacts
          path: |
            screenshots/
            *.log
            failure_page_content.html
            failure_screenshot.png
          retention-days: 7
